---
repos:

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files

- repo: https://github.com/pre-commit/pygrep-hooks
  rev: v1.10.0
  hooks:
  - id: rst-backticks     # Detect common mistake of using single backticks when writing rst
  - id: rst-inline-touching-normal     # Detect mistake of inline code touching normal text in rst

- repo: https://github.com/asottile/pyupgrade
  rev: v3.9.0
  hooks:
  - id: pyupgrade
    args: [--py38-plus]

- repo: https://github.com/ikamensh/flynt/
  rev: 1.0.0
  hooks:
  - id: flynt

- repo: https://github.com/asottile/reorder-python-imports
  rev: v3.10.0
  hooks:
  - id: reorder-python-imports
    args: [--py38-plus, --add-import, from __future__ import annotations]

# - repo: https://github.com/pre-commit/mirrors-mypy
#   rev: v1.3.0
#   hooks:
#   - id: mypy
#     additional_dependencies: [types-all]
#     files: bidspm
#     args: [--config-file, setup.cfg]

- repo: https://github.com/MarcoGorelli/auto-walrus
  rev: v0.2.2
  hooks:
  - id: auto-walrus

- repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
  rev: 0.2.3
  hooks:
  - id: yamlfmt
    args: [--mapping, '2', --sequence, '2', --offset, '0']

- repo: https://github.com/codespell-project/codespell
  rev: v2.2.5
  hooks:
  - id: codespell
    args: [--toml, pyproject.toml]
    additional_dependencies: [tomli]

- repo: https://github.com/psf/black
  rev: 23.7.0
  hooks:
  - id: black
    args: [--config, pyproject.toml]

- repo: https://github.com/pycqa/flake8
  rev: 6.0.0
  hooks:
  - id: flake8
    args: [--config, .flake8]
    additional_dependencies: [flake8-docstrings]
